name: terraform-module-setup
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
defaults:
  run:
    shell: bash

env:
  AWS_DEFAULT_REGION: us-east-1
  TEST_FOLDER: test

jobs:
  security_check:
    runs-on: ubuntu-latest
    container: 
      image: roxanapopa/docker-git-workflows:v0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running Checkov
        run: checkov -d . --skip-check CKV_AWS_60,CKV_AWS_61,CKV_AWS_62,CKV_AWS_63,CKV_AWS_70,CKV_AWS_57,CKV_AWS_20,CKV_AWS_93,CKV_AWS_18,CKV_AWS_144,CKV_AWS_19,CKV_AWS_145,CKV_AWS_21,CKV2_AWS_6

  validate:
    runs-on: ubuntu-latest
    container:
      image: roxanapopa/docker-git-workflows:v0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
  plan:
    needs: [ validate ]
    runs-on: ubuntu-latest
    container:
      image: roxanapopa/docker-git-workflows:v0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.CICD_ROLE_ARN }}
          role-session-name: cicd-session
          role-duration-seconds: 3600
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
